export default {
  at: '2024-02-02T19:06:06.238Z',
  products: [
    {
      description: 'occaecat elit officia velit',
      name: 'sint',
      price: 288.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {
      description: 'fugiat tempor incididunt irure',
      name: 'proident',
      price: 373.16,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'esse incididunt quis eiusmod',
      name: 'do',
      price: 1206.46,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'in commodo voluptate dolore',
      name: 'occaecat',
      price: 468.24,
      tmpProperty: undefined,
      activePromoId: 5,
    },
    {
      description: 'mollit ea commodo cillum',
      name: 'excepteur',
      price: 165.53,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliquip et fugiat aliqua',
      name: 'adipisicing',
      price: 1558.02,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'velit et ut ullamco',
      name: 'eu',
      price: 944.54,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {
      description: 'adipisicing fugiat duis magna',
      name: 'et',
      price: 1701.13,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ex eu Lorem dolor',
      name: 'Lorem',
      price: 252.14,
      tmpProperty: undefined,
      activePromoId: 18,
    },
    {
      description: 'elit veniam proident esse',
      name: 'ea',
      price: 472.01,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliquip nisi nulla incididunt',
      name: 'do',
      price: 528.32,
      tmpProperty: undefined,
      activePromoId: 71,
    },
    {
      description: 'laboris labore fugiat dolor',
      name: 'aliquip',
      price: 886.26,
      tmpProperty: undefined,
      activePromoId: 16,
    },
    {
      description: 'Lorem irure enim non',
      name: 'qui',
      price: 114.6,
      tmpProperty: undefined,
      activePromoId: 83,
    },
    {
      description: 'dolore labore duis ad',
      name: 'deserunt',
      price: 1666.93,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'do do ut adipisicing',
      name: 'proident',
      price: 1115.86,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'est ex ipsum adipisicing',
      name: 'est',
      price: 1092.09,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ullamco aliquip culpa do',
      name: 'tempor',
      price: 1486.21,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'elit consequat dolor ad',
      name: 'anim',
      price: 1853.35,
      tmpProperty: undefined,
      activePromoId: 54,
    },
    {
      description: 'irure fugiat officia non',
      name: 'quis',
      price: 1022.7,
      tmpProperty: undefined,
      activePromoId: 51,
    },
    {
      description: 'quis elit eiusmod sit',
      name: 'consectetur',
      price: 404.88,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'exercitation adipisicing ad laboris',
      name: 'aute',
      price: 1890.95,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laboris voluptate cupidatat adipisicing',
      name: 'fugiat',
      price: 1334.23,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {
      description: 'commodo incididunt eiusmod quis',
      name: 'occaecat',
      price: 1379.1,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ex tempor cillum culpa',
      name: 'sunt',
      price: 1741.95,
      tmpProperty: undefined,
      activePromoId: 70,
    },
    {
      description: 'anim nisi exercitation nisi',
      name: 'dolore',
      price: 1523.98,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'consequat magna aliquip sint',
      name: 'cupidatat',
      price: 1923.55,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {
      description: 'culpa duis ipsum deserunt',
      name: 'laboris',
      price: 1878.75,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'velit aliqua sit irure',
      name: 'eiusmod',
      price: 430.55,
      tmpProperty: undefined,
      activePromoId: 57,
    },
    {
      description: 'occaecat non sit ea',
      name: 'ea',
      price: 1915.17,
      tmpProperty: undefined,
      activePromoId: 70,
    },
    {
      description: 'elit commodo elit quis',
      name: 'ea',
      price: 1845.42,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: 'adipisicing nisi reprehenderit aliqua',
      name: 'exercitation',
      price: 1751.76,
      tmpProperty: undefined,
      activePromoId: 5,
    },
    {
      description: 'ullamco nulla est excepteur',
      name: 'Lorem',
      price: 436.71,
      tmpProperty: undefined,
      activePromoId: 3,
    },
    {
      description: 'irure amet nostrud eiusmod',
      name: 'consectetur',
      price: 1671.91,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aute tempor fugiat non',
      name: 'incididunt',
      price: 146.45,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'veniam consectetur Lorem ex',
      name: 'ex',
      price: 1200.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolore qui Lorem nulla',
      name: 'commodo',
      price: 1616.51,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: 'magna nostrud non nostrud',
      name: 'laborum',
      price: 1633.96,
      tmpProperty: undefined,
      activePromoId: 33,
    },
    {
      description: 'veniam duis tempor cupidatat',
      name: 'laboris',
      price: 1473.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolore do nulla do',
      name: 'laboris',
      price: 1780.92,
      tmpProperty: undefined,
      activePromoId: 2,
    },
    {
      description: 'cupidatat qui est laborum',
      name: 'culpa',
      price: 1473.94,
      tmpProperty: undefined,
      activePromoId: 5,
    },
    {
      description: 'amet ipsum ea Lorem',
      name: 'et',
      price: 1248.6,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliquip eiusmod proident ipsum',
      name: 'velit',
      price: 256.99,
      tmpProperty: undefined,
      activePromoId: 99,
    },
    {
      description: 'ullamco pariatur laborum ex',
      name: 'eu',
      price: 1180.04,
      tmpProperty: undefined,
      activePromoId: 83,
    },
    {
      description: 'esse reprehenderit labore irure',
      name: 'aute',
      price: 532.81,
      tmpProperty: undefined,
      activePromoId: 0,
    },
    {
      description: 'magna eiusmod amet mollit',
      name: 'elit',
      price: 1855.95,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: 'tempor tempor do officia',
      name: 'do',
      price: 541.81,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'commodo sit consequat deserunt',
      name: 'anim',
      price: 607.09,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliqua consequat labore amet',
      name: 'minim',
      price: 1066.48,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: 'sunt fugiat laboris minim',
      name: 'do',
      price: 198.62,
      tmpProperty: undefined,
      activePromoId: 40,
    },
    {
      description: 'velit do nostrud quis',
      name: 'ipsum',
      price: 966.66,
      tmpProperty: undefined,
      activePromoId: 10,
    },
    {
      description: 'cupidatat nisi in magna',
      name: 'sit',
      price: 124.88,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ex amet irure veniam',
      name: 'velit',
      price: 134.44,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolore sint pariatur voluptate',
      name: 'in',
      price: 244.8,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'adipisicing qui nulla aute',
      name: 'ea',
      price: 735.87,
      tmpProperty: undefined,
      activePromoId: 65,
    },
    {
      description: 'mollit dolore irure id',
      name: 'aute',
      price: 900.51,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'magna eu laboris mollit',
      name: 'sint',
      price: 887.32,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'eu qui proident dolore',
      name: 'et',
      price: 582.76,
      tmpProperty: undefined,
      activePromoId: 54,
    },
    {
      description: 'est in magna aliqua',
      name: 'anim',
      price: 598.6,
      tmpProperty: undefined,
      activePromoId: 53,
    },
    {
      description: 'sunt ut officia consequat',
      name: 'fugiat',
      price: 1002.15,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'enim proident sint laboris',
      name: 'nulla',
      price: 200,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: 'duis ullamco magna commodo',
      name: 'ex',
      price: 362.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'qui aute ex sunt',
      name: 'cupidatat',
      price: 1015.28,
      tmpProperty: undefined,
      activePromoId: 81,
    },
    {
      description: 'ipsum enim reprehenderit qui',
      name: 'eu',
      price: 960.79,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolor qui officia velit',
      name: 'magna',
      price: 815.46,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ex culpa officia excepteur',
      name: 'mollit',
      price: 378.31,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'nisi laboris duis tempor',
      name: 'consequat',
      price: 1399.62,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: 'amet eu et exercitation',
      name: 'est',
      price: 375.61,
      tmpProperty: undefined,
      activePromoId: 83,
    },
    {
      description: 'reprehenderit elit sint esse',
      name: 'culpa',
      price: 326.69,
      tmpProperty: undefined,
      activePromoId: 35,
    },
    {
      description: 'consectetur dolor exercitation elit',
      name: 'aliquip',
      price: 127.02,
      tmpProperty: undefined,
      activePromoId: 24,
    },
    {
      description: 'mollit ullamco in consectetur',
      name: 'officia',
      price: 1654.58,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laborum anim cupidatat et',
      name: 'do',
      price: 268.98,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laborum id tempor consequat',
      name: 'id',
      price: 848.87,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: 'Lorem nostrud in irure',
      name: 'laborum',
      price: 1824.58,
      tmpProperty: undefined,
      activePromoId: 58,
    },
    {
      description: 'do tempor culpa anim',
      name: 'amet',
      price: 1816.5,
      tmpProperty: undefined,
      activePromoId: 5,
    },
    {
      description: 'sint ut et culpa',
      name: 'consequat',
      price: 571.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'minim sint aute est',
      name: 'et',
      price: 1750.94,
      tmpProperty: undefined,
      activePromoId: 51,
    },
    {
      description: 'enim sunt ut et',
      name: 'aliquip',
      price: 1585.74,
      tmpProperty: undefined,
      activePromoId: 6,
    },
    {
      description: 'esse nisi velit irure',
      name: 'magna',
      price: 1350.78,
      tmpProperty: undefined,
      activePromoId: 96,
    },
    {
      description: 'non occaecat duis anim',
      name: 'et',
      price: 1213.27,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'anim tempor amet ut',
      name: 'sunt',
      price: 1611.73,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: 'officia ad cupidatat consectetur',
      name: 'veniam',
      price: 1690.72,
      tmpProperty: undefined,
      activePromoId: 80,
    },
    {
      description: 'ad tempor aute ea',
      name: 'qui',
      price: 177.79,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'consequat proident do cillum',
      name: 'in',
      price: 1321.13,
      tmpProperty: undefined,
      activePromoId: 51,
    },
    {
      description: 'velit sunt elit excepteur',
      name: 'incididunt',
      price: 170.98,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'occaecat non aliqua adipisicing',
      name: 'mollit',
      price: 357.12,
      tmpProperty: undefined,
      activePromoId: 32,
    },
    {
      description: 'officia ullamco laborum enim',
      name: 'culpa',
      price: 1304.05,
      tmpProperty: undefined,
      activePromoId: 77,
    },
    {
      description: 'excepteur aliqua aute sit',
      name: 'esse',
      price: 893.03,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'velit cillum culpa fugiat',
      name: 'eiusmod',
      price: 508.23,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: 'eiusmod proident sint et',
      name: 'labore',
      price: 1886.42,
      tmpProperty: undefined,
      activePromoId: 23,
    },
    {
      description: 'magna esse proident in',
      name: 'aute',
      price: 516.41,
      tmpProperty: undefined,
      activePromoId: 3,
    },
    {
      description: 'ullamco cupidatat excepteur laboris',
      name: 'Lorem',
      price: 962.62,
      tmpProperty: undefined,
      activePromoId: 23,
    },
    {
      description: 'in anim culpa cupidatat',
      name: 'laborum',
      price: 613.41,
      tmpProperty: undefined,
      activePromoId: 85,
    },
    {
      description: 'tempor excepteur proident ut',
      name: 'eu',
      price: 1574.43,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'eiusmod pariatur ullamco quis',
      name: 'quis',
      price: 1375.23,
      tmpProperty: undefined,
      activePromoId: 15,
    },
    {
      description: 'et dolore sit non',
      name: 'nostrud',
      price: 1873.84,
      tmpProperty: undefined,
      activePromoId: 15,
    },
    {
      description: 'sit dolore consequat sit',
      name: 'exercitation',
      price: 1884.66,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'id velit id irure',
      name: 'amet',
      price: 1402.48,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'nostrud dolore minim incididunt',
      name: 'ex',
      price: 1303.35,
      tmpProperty: undefined,
      activePromoId: 74,
    },
    {
      description: 'laboris exercitation anim dolor',
      name: 'incididunt',
      price: 112.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'occaecat duis consectetur enim',
      name: 'esse',
      price: 1237.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {},
  ],
};
